### ISSUE TITLE
Not compatible with Capacitor 5.0

### ISSUE THREAD

**Issue by ggarg2** [razorpay/razorpay-capacitor#70]
Hi Team,

Razorpay capacitor is not working with Capacitor 5.

**Comment by Aksoom-Hussain** [comment]
after migrating from 4.0 to 5.0 it stopped working

**Comment by shravin** [comment]
Is razorpay working on upgrading this repo to support Capacitor 5? It will be extremely helpful to have one. Thank you very much.

**Comment by ggarg2** [comment]
Not sure if they are going to upgrade this plugin.

**Comment by skadimoolam** [comment]
Hi @Nautiyalsachin @vivekshindhe 
Are there any plans to update this package to support Capacitor 5

**Comment by adnanganie** [comment]
I think they are not working on this project anymore, better is to use cordova version

**Comment by vivekshindhe** [comment]
Hey folks,  capacitor-v5 enabled SDK is present in the branch `f/capacitor-v5`.
We didn't want to break things for people using a lower version since quite a few changes required for the migration are breaking changes.
The installation for v5 would be

```npm install https://github.com/razorpay/razorpay-capacitor.git#f/capacitor-v5```

We are now looking into pushing this to npm to allow us to maintain separate versioning for different capacitor versions.
