### ISSUE TITLE
Capacitor 5 support Not available

### ISSUE THREAD

**Issue by genorainfo** [razorpay/razorpay-capacitor#73]
HI,
Current plugin is not supported with capacitor 5
Can you please provide plugin compatible with Capacitor 5

**Comment by shravin** [comment]
@vivekshindhe how can I help to make the plugin to support capacitor 5? Any link to developer documentation will help to send a PR to you. Looking at capacitor 4 upgrade PR, capacitor 5 upgrade PR should be even simpler. Let me know.

**Comment by malcolm2xd** [comment]
🚀 Hi team! Excited about Capacitor 5! 
Any chance we could get a release that supports it? Thanks! 🙌

**Comment by adnanganie** [comment]
Could you please provide clarity on when support for Capacitor 5 with Ionic is expected to be available

**Comment by vivekshindhe** [comment]
@adnanganie Hey, capacitor-v5 enabled SDK is present in the branch 
`f/capacitor-v5`. We didn't want to break things for people using a lower version since quite a few changes required for the migration are breaking changes.
The installation for v5 would be
`npm install https://github.com/razorpay/razorpay-capacitor.git#f/capacitor-v5`

We are now looking into pushing this to npm to allow us to maintain separate versioning for different capacitor versions.
